image: maven:3.6.3-jdk-14

stages:
  - build
  - test
  - style
  - docs
  - debug

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    - merge_request

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test jacoco:report
    - cat target/site/jacoco/index.html
  only:
    - merge_request

format:
  stage: style
  script:
    - mvn $MAVEN_CLI_OPTS spotless:check
  only:
    - merge_request

lint:
  stage: style
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check
  only:
    - merge_request

javadoc:
  stage: docs
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:javadoc
  only:
    - merge_request

ci:
  stage: debug
  script:
    - ./.gitlab/scripts/gitlab-ci-info.sh
  only:
    - merge_request
  when: on_failure

pages:
  stage: docs
  script:
    - mvn $MAVEN_CLI_OPTS site:site
    - mv target/site public/
  only:
    - master
    - main
  artifacts:
    paths:
      - public/
